module.exports=[
    {
        id:1,
        title:"The Four Agreements: A Practical Guide to Personal Freedom",
        author:"Miguel Ruiz",
        comment:"My favourite read. A great read to escape too!",
        library_id:82540,
    },
    {
        id:2,
        title:"Breakfast at Tiffany's",
        author:"Truman Capote",
        comment:"My favourite read. A great read to escape too!",
        library_id:82540,
    },
    {
        id:3,
        title:"Artemis Fowl",
        author:"Eoin Colfer",
        comment:"My favourite read. A great read to escape too!",
        library_id:130554,
    },
    {
        id:4,
        title:"Othello",
        author:"William Shakespeare",
        comment:"My favourite read. A great read to escape too!",
        library_id:130554,
    },
    {
        id:5,
        title:"Atonement",
        author:"Ian McEwan",
        comment:"My favourite read. A great read to escape too!",
        library_id:31614,
    },
    {
        id:6,
        title:"Flowers for Algernon",
        author:"Daniel Keyes",
        comment:"My favourite read. A great read to escape too!",
        library_id:31614,
    },
    {
        id:7,
        title:"A Christmas Carol",
        author:"Charles Dickens",
        comment:"My favourite read. A great read to escape too!",
        library_id:96166,
    },
    {
        id:8,
        title:"Much Ado About Nothing",
        author:"William Shakespeare",
        comment:"White Oleander",
        library_id:96166,
    },
    {
        id:9,
        title:"Watchmen",
        author:"Alan Moore",
        comment:"My favourite read. A great read to escape too!",
        library_id:108239,
    },
    {
        id:10,
        title:"The Night Circus",
        author:"Erin Morgenstern",
        comment:"My favourite read. A great read to escape too!",
        library_id:108239,
    },
    {
        id:11,
        title:"A Wrinkle in Time",
        author:"Madeleine L'Engle",
        comment:"My favourite read. A great read to escape too!",
        library_id:126744,
    },
    {
        id:12,
        title:"Shōgun",
        author:"James Clavell",
        comment:"My favourite read. A great read to escape too!",
        library_id:126744,
    },
    {
        id:13,
        title:"Lips of a Mastodon",
        author:"Ted Bernal Guevara",
        comment:"My favourite read. A great read to escape too!",
        library_id:88728,
    },
    {
        id:14,
        title:"The Five People You Meet in Heaven",
        author:"Mitch Albom",
        comment:"My favourite read. A great read to escape too!",
        library_id:88728,
    },
    {
        id:15,
        title:"Uncle Tom's Cabin",
        author:"Harriet Beecher Stowe",
        comment:"My favourite read. A great read to escape too!",
        library_id:77845,
    },
    {
        id:16,
        title:"House of Leaves",
        author:"Mark Z. Danielewski",
        comment:"My favourite read. A great read to escape too!",
        library_id:77845,
    },
    {
        id:17,
        title:"Utopia",
        author:"Thomas More",
        comment:"My favourite read. A great read to escape too!",
        library_id:44685,
    },
    {
        id:18,
        title:"The Red Tent",
        author:"Anita Diamant",
        comment:"My favourite read. A great read to escape too!",
        library_id:44685,
    },
    {
        id:19,
        title:"How the Grinch Stole Christmas!",
        author:"Dr. Seuss",
        comment:"My favourite read. A great read to escape too!",
        library_id:69912,
    },
    {
        id:20,
        title:"The Idiot",
        author:"Fyodor Dostoyevsky",
        comment:"My favourite read. A great read to escape too!",
        library_id:69912,
    },
    {
        id:21,
        title:"Goodnight Moon",
        author:"Margaret Wise Brown",
        comment:"My favourite read. A great read to escape too!",
        library_id:84229,
    },
    {
        id:22,
        title:"Letters to a Young Poet",
        author:"Rainer Maria Rilke",
        comment:"My favourite read. A great read to escape too!",
        library_id:84229,
    },
    {
        id:23,
        title:"Breaking Dawn",
        author:"Stephenie Meyer",
        comment:"My favourite read. A great read to escape too!",
        library_id:8963,
    },
    {
        id:24,
        title:"The Jungle",
        author:"Upton Sinclair",
        comment:"My favourite read. A great read to escape too!",
        library_id:8963,
    },
    {
        id:25,
        title:"The Perks of Being a Wallflower",
        author:"Stephen Chbosky",
        comment:"My favourite read. A great read to escape too!",
        library_id:86493,
    },
    {
        id:26,
        title:"Much Ado About Nothing",
        author:"William Shakespeare",
        comment:"My favourite read. A great read to escape too!",
        library_id:86493,
    },
    {
        id:27,
        title:"A Farewell to Arms",
        author:"Ernest Hemingway",
        comment:"My favourite read. A great read to escape too!",
        library_id:48354,
    },
    {
        id:28,
        title:"The House on Mango Street",
        author:"Sandra Cisneros",
        comment:"My favourite read. A great read to escape too!",
        library_id:48354,
    },
    {
        id:29,
        title:"John Adams",
        author:"David McCullough",
        comment:"My favourite read. A great read to escape too!",
        library_id:27003,
    },
    {
        id:30,
        title:"The Fiery Cross",
        author:"Diana Gabaldon",
        comment:"My favourite read. A great read to escape too!",
        library_id:27003,
    },
    {
        id:31,
        title:"Bridget Jones's Diary",
        author:"Helen Fielding",
        comment:"My favourite read. A great read to escape too!",
        library_id:25331,
    },
    {
        id:32,
        title:"Lunar Park",
        author:"Bret Easton Ellis",
        comment:"My favourite read. A great read to escape too!",
        library_id:25331,
    },
    {
        id:33,
        title:"Anne of Green Gables",
        author:"L.M. Montgomery",
        comment:"My favourite read. A great read to escape too!",
        library_id:81867,
    },
    {
        id:34,
        title:"The Great Gatsby",
        author:"F. Scott Fitzgerald",
        comment:"My favourite read. A great read to escape too!",
        library_id:81867,
    },
    {
        id:35,
        title:"The Godfather",
        author:"Mario Puzo",
        comment:"My favourite read. A great read to escape too!",
        library_id:134242,
    },
    {
        id:36,
        title:"Different Seasons",
        author:"Stephen King",
        comment:"My favourite read. A great read to escape too!",
        library_id:134242,
    },
    {
        id:37,
        title:"The Goldfinch",
        author:"Donna Tartt",
        comment:"My favourite read. A great read to escape too!",
        library_id:64049,
    },
    {
        id:38,
        title:"Exodus",
        author:"Leon Uris",
        comment:"My favourite read. A great read to escape too!",
        library_id:64049,
    },
    {
        id:39,
        title:"Fahrenheit 451",
        author:"Ray Bradbury",
        comment:"My favourite read. A great read to escape too!",
        library_id:122730,
    },
    {
        id:40,
        title:"American Psycho",
        author:"Bret Easton Ellis",
        comment:"My favourite read. A great read to escape too!",
        library_id:122730,
    },

];