module.exports = [
  {
    id: 82540,
    name: "Louis Brier Home & Hospital",
    address: "1055 West 41st Ave",
    region: "Vancouver, BC",
    lat: 49.2344818,
    lng: -123.1292635,
    description:
      "This library was created and decorated in collaboration with residents, staff and VanCity.",
  },
  {
    id: 130554,
    name: "The Not-So-Little Free Library",
    address: "4854 Ontario Street",
    region: "Vancouver, BC",
    lat: 49.24131,
    lng: -123.10497,
    description:
      "Given its not-so-little size, stewards of nearby LFLs are welcomed to bring over overflow books if theirs become too crowded.",
  },
  {
    id: 31614,
    name: "Yellow House Library",
    address: "4991 Prince Edward St",
    region: "Vancouver, BC",
    lat: 49.23979,
    lng: -123.0973,
    description:
      "It has become a hub of the neighbourhood since we added a bench across from it; parents read to their children there, others sit with a book and chat to neighbours walking by. Literacy is a gift and we're happy to share it!",
  },
  {
    id: 96166,
    name: "Peveril Little Free Library",
    address: "87 Peveril Ave",
    region: "Vancouver, BC",
    lat: 49.2465305,
    lng: -123.1073939,
    description:
      "The Peveril Library has a variety of books for people in the neighborhood to enjoy at home or as they relax in Hillcrest park.",
  },
  {
    id: 108239,
    name: "St Mary’s Kerrisdale Little Free Library",
    address: "2490 W 37Th Avenue",
    region: "Vancouver, BC",
    lat: 49.23818379999999,
    lng: -123.1622296,
    description:
      "This little free library is a gift to the community from St Mary’s Kerrisdale! Crafted and donated by Ron Kessler",
  },
  {
    id: 126744,
    name: "Four Seguin's Free Library",
    address: "2963 West 31St Ave",
    region: "Vancouver, BC",
    lat: 49.24448,
    lng: -123.17192,
    description:
      "The best thing about the pandemic was the time it gave us to devote to this little project. I hope it brings everyone as much joy as it has brought to us",
  },
  {
    id: 88728,
    name: "The John Liket Memorial Library",
    address: "3005 Heather Street",
    region: "Vancouver, BC",
    lat: 49.2584588,
    lng: -123.1204121,
    description:
      "To honour my Dad’s passing we’ve combined my love of books with his love of making things. Plus, he loved to salvage free stuff!",
  },
  {
    id: 77845,
    name: "Historic Joy Kogawa House",
    address: "1450 West 64th Avenue",
    region: "Vancouver, BC",
    lat: 49.2128612,
    lng: -123.1384685,
    description:
      "Our Little Free Library with its wood shingle siding shows the way the house looked in the late 1930s when author Joy Kogawa lived there as a child. Our goal is to keep the free library filled with books to share.",
  },
  {
    id: 44685,
    name: "Vancouver Self Storage",
    address: "8700 Barnard St",
    region: "Vancouver, BC",
    lat: 49.206776,
    lng: -123.1450258,
    description:
      "Our Little Free Library, ‘Owlbert Einstein,’ landed on our front lawn in September 2016. We also have some seats here for you if you’re too eager to get reading! We look forward to exchanging some of our favourites with you!",
  },
  {
    id: 69912,
    name: "West 10th",
    address: "2294 West 10th Ave",
    region: "Vancouver, BC",
    lat: 49.2626607,
    lng: -123.157276,
    description:
      "We created our first Little Library as a high school shop project. It was part of our 'Week Without Walls' event in which our school reaches out to our community.",
  },
  {
    id: 84229,
    name: "Barking Bichons Neighborhood Bookhouse",
    address: "2515 West 6th Avenue",
    region: "Vancouver, BC",
    lat: 49.26682,
    lng: -123.16281,
    description:
      "This was built as a birthday gift for me, by my sister and very talented brother in law. Our LFL reflects my love of reading and community as well as the barking Bichon Frise dogs in our home, who love to engage anyone stopping by.",
  },
  {
    id: 8963,
    name: "Kellie Diguangco",
    address: "1249 Cartwright Street",
    region: "Vancouver, BC",
    lat: 49.2699647,
    lng: -123.133215,
    description:
      "Granville Island is a charming place; home to art schools and studios to many artisans. Kellie is a Literacy advocate, lover of children's books, imagination aficionado, instructor, and mom of 4. Kellie hopes to continue to spread the love of Literacy",
  },
  {
    id: 86493,
    name: "Roxies Reads",
    address: "3205 West King Edward Ave",
    region: "Vancouver, BC",
    lat: 49.2503326,
    lng: -123.1759721,
    description:
      "I love reading and I found my bookshelves filling up and that's not the purpose of books. Feel free to take books without dropping off but if you have some to share I would love you to place them here. Happy Reading!",
  },
  {
    id: 48354,
    name: "Brin Hamilton",
    address: "4324 Prince Edward St",
    region: "Vancouver, BC",
    lat: 49.2463477,
    lng: -123.096589,
    description: "Take a book leave a book!",
  },
  {
    id: 27003,
    name: "Adera",
    address: "6237 Adera Street",
    region: "Vancouver, BC",
    lat: 49.2294259,
    lng: -123.1439104,
    description: "Take a book leave a book!",
  },
  {
    id: 25331,
    name: "Kitsilano",
    address: "2265 W 14th Avenue",
    region: "Vancouver, BC",
    lat: 49.2594578,
    lng: -123.1569832,
    description: "Take a book leave a book!",
  },
  {
    id: 81867,
    name: "Victoria Dr",
    address: "4761 Little St",
    region: "Vancouver, BC",
    lat: 49.2421035,
    lng: -123.0642535,
    description: "Newly erected on Jan 27, 2019! Come visit our LFL!",
  },
  {
    id: 134242,
    name: "The Book Haus",
    address: "2872 West 33Rd Avenue",
    region: "Vancouver, BC",
    lat: 49.24203,
    lng: -123.16959,
    description: "Take a book leave a book!",
  },
  {
    id: 64049,
    name: "UBC",
    address: "UBC Press, 2029 West Mall",
    region: "Vancouver, BC",
    lat: 49.2648341,
    lng: -123.2559809,
    description:
      "At UBC Press we are a community of book lovers and we wanted to share our love of books with the greater UBC Community and visitors. We chose to build our Little Library to mimic the structure where UBC Press is located, Ponderosa Annex B.",
  },
  {
    id: 122730,
    name: "Hastings-Sunrise Little Library",
    address: "2006 Franklin St",
    region: "Vancouver, BC",
    lat: 49.28184,
    lng: -123.06331,
    description:
      "Thank you to neighbourhood small grants for making our free little library a reality! We have a constant flow of adult/childrens books available for everyone! Come by and take whatever you need.",
  },
];
